version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: mi_postgres
    environment:
      POSTGRES_USER: Rose
      POSTGRES_PASSWORD: Rose123
      POSTGRES_DB: Spoty_bd
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: